apiVersion: v1
kind: PersistentVolume
metadata:
  name: web-pv
  labels:
    name: web-pv 
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  hostPath:
    path: /mnt/data/sitio-web