apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: web-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: ""
  selector:
    matchLabels:
      name: web-pv
  resources:
    requests:
      storage: 1Gi
